version: "3.4"

# サービス設定
services:

  # database (mysql)
  db:
    restart:  on-failure:10
    build:    ./docker/db
    env_file: ./docker/db/.env

  # adminer (database manager)
  adminer:
    restart:   on-failure:10
    build:     ./docker/adminer
    env_file:  ./docker/adminer/.env
    ports:      [ 9105:8080 ]
    depends_on: [ db ]

  # php-fpm
  php:
    restart:  on-failure:10
    build:    ./docker/php
    env_file: ./docker/php/.env
    depends_on: [ db ]
    volumes:
      - ./html:/var/www/html
      - ./docker/php/conf:/usr/local/etc/php-fpm.d

  web:
    restart:    on-failure:10
    build:      ./docker/web
    env_file:   ./docker/web/.env
    ports:      [ 9100:80 ]
    depends_on: [ php ]
    volumes:
      - ./html:/var/www/html
      - ./docker/web/conf:/etc/nginx/conf.d


