version: "3.4"

# サービス設定
services:

  # database (mysql)
  db:
    restart:  on-failure:10
    build:    ./docker/db
    env_file: ./docker/db/.env
    ports: 
      - 3306:3306
    volumes:
      - ./docker/db/migrations:/docker-entrypoint-initdb.d
      - ./docker/db/conf:/etc/mysql/mysql.conf.d

  # redis (session)
  redis:
    restart:  on-failure:10
    build:    ./docker/redis
    env_file: ./docker/redis/.env

  # adminer (database manager)
  adminer:
    restart:  on-failure:10
    build:    ./docker/adminer
    env_file: ./docker/adminer/.env
    ports:
      - 9105:8080
    depends_on:
      - db

  # php-fpm
  php:
    restart:  on-failure:10
    build:    ./docker/php
    env_file: ./docker/php/.env
    command: "sh -C /var/www/html/run.sh"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf:/usr/local/etc/php-fpm.d

  # httpd
  web:
    restart:    on-failure:10
    build:      ./docker/web
    env_file:   ./docker/web/.env
    ports:
      - 9100:80
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/web/conf:/etc/nginx/conf.d


